In [1]:
pwd

'C:\\Users\\studio'

In [2]:
print("WORKSHOP ON PYTHON")

WORKSHOP ON PYTHON


In [4]:
print('ZHI')

ZHI


In [5]:
print('a\'a\'')

a'a'


In [6]:
print('''a 'vishal' ''')

a 'vishal' 


In [7]:
print('''
data
science
zhi
''')


data
science
zhi



print

# Arithmetic Operation

In [8]:
2+5

7

In [9]:
6-3

3

In [10]:
3*6

18

In [11]:
6/3

2.0

In [12]:
6//3

2

In [13]:
2e2

200.0

In [14]:
5*5+8*2

41

In [15]:
(5+5)*2

20

In [18]:
x=10
x

10

20

In [21]:
print(x)

20


20

In [23]:
x=20

In [24]:
x

20

In [25]:
print(x)

20


In [26]:
type(x)

int

In [27]:
print(type(x))

<class 'int'>


In [28]:
s='workshop'

In [29]:
s

'workshop'

# Slicing and Indexing

s[start:end:step]

In [30]:
s[:]

'workshop'

In [31]:
s[: :]

'workshop'

In [32]:
s[5]

'h'

In [33]:
s[:5]

'works'

In [34]:
s[3:]

'kshop'

In [35]:
s[: :2]

'wrso'

In [36]:
s[: :-1]

'pohskrow'

# Methods

In [37]:
s=s.upper()

In [38]:
s

'WORKSHOP'

In [39]:
s.lower()

'workshop'

split

In [41]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [42]:
'A B C D E'.split('C')

['A B ', ' D E']

In [43]:
s.split('S')

['WORK', 'HOP']

In [44]:
name='virat'
run=100

In [46]:
print(name+str(run))

virat100


# Formating

In [47]:
print('this is a %s pen', 'ram')

this is a %s pen ram


In [49]:
print('this is a %s pen %s' %('ram','abc'))

this is a ram pen abc


# LIST

In [50]:
my_list='A B C D'.split()

In [51]:
my_list

['A', 'B', 'C', 'D']

In [52]:
mylist=['a',5,5.3]

In [53]:
mylist

['a', 5, 5.3]

In [54]:
print(type(mylist))

<class 'list'>


# Slicing and Indexing

In [55]:
mylist[1]

5

In [56]:
mylist[0:2]

['a', 5]

In [57]:
mylist[0:3:1]

['a', 5, 5.3]

In [58]:
mylist[0:3:2]

['a', 5.3]

In [59]:
mylist*2

['a', 5, 5.3, 'a', 5, 5.3]

In [60]:
mylist=mylist + ['a']

In [61]:
mylist

['a', 5, 5.3, 'a']

# LIST METHOD

In [62]:
l=[1,2,3,4,5]

In [63]:
l

[1, 2, 3, 4, 5]

In [64]:
l.append('A B C'.split())

In [65]:
l

[1, 2, 3, 4, 5, ['A', 'B', 'C']]

In [66]:
l.append('A')

In [67]:
l

[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'A']

In [68]:
print(l)

[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'A']


In [69]:
list1=[1,2,3,4,5]

In [70]:
list1

[1, 2, 3, 4, 5]

In [71]:
print(list)

<class 'list'>


In [74]:
print(type(list))

<class 'type'>


In [73]:
list1.append('a')
list1

[1, 2, 3, 4, 5, 'a', 'a']

In [75]:
list1

[1, 2, 3, 4, 5, 'a', 'a']

In [76]:
l1=[1,2,3]
l2=[4,5,6]
l3=[6,7,8]

In [77]:
matrix=[l1,l2,l3]

In [78]:
matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [79]:
type(matrix)

list

In [80]:
matrix[1][0]

4

In [81]:
len(matrix)

3

# Touple

In [82]:
t1=(1,2,3)

In [83]:
t1

(1, 2, 3)

In [84]:
type(t1)

tuple

In [85]:
print(type(t1))

<class 'tuple'>


In [86]:
t1

(1, 2, 3)

In [87]:
l2=[1,2,3]

In [88]:
l2[2]=5

In [90]:
l2

[1, 2, 5]

In [91]:
t1[1]

2

In [92]:
t1[-1]

3

# Touple Method

In [93]:
t1.index(2)

1

In [94]:
t1.count(3)

1

# Dictionary

In [95]:
 disc1={1:'a',2:'b',3:'c'}

In [96]:
disc1

{1: 'a', 2: 'b', 3: 'c'}

In [97]:
type(disc1)

dict

In [98]:
print(type(disc1))

<class 'dict'>


In [99]:
disc1[1]

'a'

In [100]:
disc1[2]

'b'

In [101]:
disc1[4]='ram'

In [102]:
disc1

{1: 'a', 2: 'b', 3: 'c', 4: 'ram'}

# Nested Dictionary

In [108]:
disc1={1:'a',2:'b','key1':{1:'a',2:'hello',3:'c'},3:'c'}

In [109]:
disc1

{1: 'a', 2: 'b', 'key1': {1: 'a', 2: 'hello', 3: 'c'}, 3: 'c'}

In [110]:
disc1['key1'][2][2]

'l'

In [111]:
disc1['key1'][2]

'hello'

# Method

In [113]:
disc1.keys()

dict_keys([1, 2, 'key1', 3])

In [114]:
disc1.values()

dict_values(['a', 'b', {1: 'a', 2: 'hello', 3: 'c'}, 'c'])

In [115]:
disc1.items()

dict_items([(1, 'a'), (2, 'b'), ('key1', {1: 'a', 2: 'hello', 3: 'c'}), (3, 'c')])

# Set

# Unodered Collection

In [116]:
x=set()

In [117]:
x

set()

In [118]:
type(x)

set

In [119]:
print(type(x))

<class 'set'>


In [120]:
x.add(1)

In [121]:
x

{1}

In [122]:
list2=[1,2,3,1,2,3,2,2,3,4]

In [123]:
list2

[1, 2, 3, 1, 2, 3, 2, 2, 3, 4]

In [124]:
set(list2)

{1, 2, 3, 4}

### Boolean

In [125]:
True

True

In [126]:
False

False

In [127]:
None

In [128]:
pwd

'C:\\Users\\studio'

In [129]:
list3=[1,2,[3,4,'hello']]

In [130]:
list3

[1, 2, [3, 4, 'hello']]

In [132]:
list3[2][2]='goodbye'

In [133]:
list3

[1, 2, [3, 4, 'goodbye']]

In [134]:
list5=[1,2,2,33,4,4,11,22,3,3,2]

In [135]:
list5

[1, 2, 2, 33, 4, 4, 11, 22, 3, 3, 2]

In [136]:
set(list5)

{1, 2, 3, 4, 11, 22, 33}

## Membership Operator

In [137]:
m='zhipatna'

In [138]:
m

'zhipatna'

In [139]:
'p' in m

True

In [140]:
't' not in m

False

In [141]:
x=100

In [142]:
y=100

In [143]:
x is y

True

In [144]:
x is not y

False

In [145]:
list1=[1,2,3]

In [146]:
list2=[1,2,3]

In [148]:
list1 is list2

False

In [150]:
list1 == list2

False

# Numerical Python

In [151]:
import numpy as np

In [152]:
x=[1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [153]:
type(x)

list

In [154]:
y=np.array(x)

In [155]:
type(y)

numpy.ndarray

In [156]:
x2=(1,2,3,'NTELIT',3.4)

In [157]:
np.array(x2)

array(['1', '2', '3', 'NTELIT', '3.4'], dtype='<U11')

# Linspace

In [159]:
np.linspace(start=0, stop=20, num=10,endpoint=False,retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [160]:
np.linspace(start=0, stop=20, num=10, endpoint=True,retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

# Arange

In [161]:
np.arange(start=0,stop=50,step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [162]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [163]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [164]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

# Create 3*3 Array

In [166]:
z=[[1,2,3],[4,5,6],[7,8,9]]

In [167]:
z

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [169]:
y=np.array(z)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [171]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [172]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Reshaping

In [173]:
x=np.array([0,1,2,3,4,5,6,7,8,9])

In [174]:
x #1*10 type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Convert to 5*2

In [175]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [176]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [177]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Sliceing

In [178]:
a=np.arange(10)

In [179]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
s=slice(2,7)

In [181]:
a[s]

array([2, 3, 4, 5, 6])

In [182]:
s1=slice(2,7,2)

In [183]:
a[s1]

array([2, 4, 6])

In [184]:
a[2:7]

array([2, 3, 4, 5, 6])

In [185]:
a[2:7:2]

array([2, 4, 6])

# Random Number Generation

In [186]:
np.random.rand(5)

array([0.49145832, 0.99731728, 0.57884336, 0.2239455 , 0.02305833])

In [187]:
np.random.rand(5)

array([0.97157824, 0.15483264, 0.35180975, 0.7014494 , 0.05238624])

# Normal Distribution

In [188]:
np.random.rand(5,4)

array([[0.23285608, 0.02740352, 0.9739287 , 0.60550998],
       [0.65779248, 0.26661677, 0.35928848, 0.46455018],
       [0.0672243 , 0.56335148, 0.3362253 , 0.44227137],
       [0.85626271, 0.05203666, 0.85054462, 0.74833837],
       [0.03302591, 0.71696675, 0.95775924, 0.90829252]])

# Randint

In [189]:
np.random.randint(low=0,high=100)

42

In [193]:
# 4 digit Random Number
np.random.randint(low=1000,high=9999)

9117

In [194]:
np.random.randint(low=1000,high=9999,size=10)

array([8542, 4169, 5856, 3928, 8254, 8401, 2576, 6174, 2990, 3803])

# Seed

In [195]:
 np.random.seed(23)
np.random.rand(4)   

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [196]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])